name: Check for Secrets
on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Secret Scanner
        uses: secret-scanner/action@55e02af12a6a3b838c0138747c82d6181c179ebe # 0.0.2
